* pass out error

diff --git a/.github/workflows/unittests_docker.yml b/.github/workflows/unittests_docker.yml
--- a/.github/workflows/unittests_docker.yml
+++ b/.github/workflows/unittests_docker.yml
@@ -16,9 +16,8 @@ jobs:
       - name: Test with pytest
         run: |
           cd deployment
-          try {
-            bash launch-tests.sh
-          } catch (error) {
-            core.setFailed(error.message);
-          }
+          if $(launch-tests.sh) ; then
+            echo "Failure!"
+            exit 1
+          fi
         
